# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/SNetFramework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:

- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'gitversion.yml'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: UseDotNet@2
  displayName: 'Install .Net Core'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '/p:AssemblyVersion=$(GitVersion.ASSEMBLYSEMFILEVER)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: "Pack NuGet packages"
  inputs:
    command: 'pack'
    packagesToPack: '$(solution)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/NuGet'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.NuGetVersion'
    buildProperties: '/p:AssemblyVersion=$(GitVersion.ASSEMBLYSEMFILEVER)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: "Publish to Azure DevOps"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/NuGet/*.nupkg;!$(Build.ArtifactStagingDirectory)/NuGet/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e745086d-201a-4e45-8d8f-ed7088052af8'

- task: NuGetCommand@2
  displayName: "Publish Symbol to GitHub Packages"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/NuGet/*.snupkg;!$(Build.ArtifactStagingDirectory)/NuGet/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'GitHub JaSaSe NuGet'  

- task: NuGetCommand@2
  displayName: "Publish to GitHub Packages"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/NuGet/*.nupkg;!$(Build.ArtifactStagingDirectory)/NuGet/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'GitHub JaSaSe NuGet'  