# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/SNetFramework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:

- task: GitVersion@5
  inputs:
    runtime: 'core'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(solution)'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.NuGetVersion'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src'
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/NuGet'
    CleanTargetFolder: true
    flattenFolders: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/NuGet/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'GitHub JaSaSe NuGet'